---
title: "practice_data"
author: "Lucy He"
date: "3/26/2020"
output: html_document
---


# This deleted .Rmd used to create confidence intervals based on fake data generated within the sheet

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(readxl)
library(reprex)
library(janitor)
library(gt)
library(shiny)
library(infer)
library(googlesheets4)
```

```{r}
# reads in from the "first_years"
# google sheet in the project drive

sheets_deauth()
  
sheet <- read_sheet(ss= "https://docs.google.com/spreadsheets/d/18Nbt_VtV1YARn311z0t2z9vh5DuzAVCGLJrvRsqHuLs/edit#gid=1531565679") %>%
  clean_names()
```

```{r clean_names, echo = FALSE}

# takes the sheet of first_years
# and reassigns column names

# clean column_names
names(sheet)[names(sheet) == "ethnicity_check_all_that_apply"]<-"ethnicity"
names(sheet)[names(sheet) == "religion_check_all_that_apply"] <- "religion"
names(sheet)[names(sheet) == "are_you_an_international_student"] <- "international"
names(sheet)[names(sheet) == "are_you_an_international_student"] <- "international"
names(sheet)[names(sheet) == "if_you_answered_yes_to_being_an_international_student_what_country_are_you_from"]<- "country"
names(sheet)[names(sheet) == "if_you_answered_yes_to_being_a_varsity_athlete_what_sport_do_you_play_on"]<- "sport"
names(sheet)[names(sheet) == "are_you_a_varsity_athlete"]<- "varsity"
names(sheet)[names(sheet)=="if_you_answered_yes_to_being_a_legacy_student_what_house_was_your_relative_in"]<- "relative_house"
names(sheet)[names(sheet) == "are_you_on_any_financial_aid"]<- "financial_aid"
names(sheet)[names(sheet) == "what_is_your_blocking_group_size"]<-"group_size"
names(sheet)[names(sheet)=="what_is_your_blocking_group_name_all_lowercase_with_no_spaces"]<- "group_name"
names(sheet)[names(sheet)=="what_is_your_blocking_group_leaders_name_first_and_last_ex_john_doe"]<- "group_leader"
names(sheet)[names(sheet)=="are_you_blocking_with_any_of_your_suitemates"]<- "suitemates"
names(sheet)[names(sheet)=="what_house_were_you_placed_in"]<- "house"
names(sheet)[names(sheet)=="if_you_are_linking_please_provide_the_first_and_last_name_of_one_person_from_your_linking_group"] <- "linking_group"
names(sheet)[names(sheet)=="please_list_all_members_in_your_blocking_group_separated_by_commas_first_and_last_ex_john_doe_john_harvard"]<- "group_members"
sheet
```

```{r assign_class}

# takes the sheet of first_years
# and assigns the correct class
# to each variable. Variables like
# 'religion' and 'ethnicity' are 
# given numeric values. The numeric
# values are defined later on (eg 
# when ethnicity == 1, it means that
# the ethnicity is White.)

sheet <- sheet %>% 
  mutate(first_name = as.character(first_name)) %>% 
  mutate(last_name = as.character(last_name)) %>% 
  mutate(freshman_dorm = as.character(freshman_dorm)) %>% 
  mutate(entryway = as.character(entryway)) %>% 
  mutate(sex = as.logical(sex)) %>% 
  mutate(ethnicity = as.numeric(ethnicity)) %>% 
  mutate(religion = as.character(religion)) %>% 
  mutate(sexual_orientation = as.character(sexual_orientation)) %>%
  mutate(international = as.logical(international)) %>%
  mutate(country = as.character(country)) %>% 
  mutate(varsity = as.logical(varsity)) %>%
  mutate(sport = as.character(sport)) %>%
  mutate(legacy = as.logical(legacy)) %>%
  mutate(relative_house = as.character(relative_house)) %>%
  mutate(financial_aid = as.logical(financial_aid)) %>%
  mutate(suitemates = as.character(suitemates)) %>% 
  mutate(group_size = as.numeric(group_size)) %>%
  mutate(group_name = as.numeric(group_name)) %>%
  mutate(group_leader = as.character(group_leader)) %>%
  mutate(group_members = as.character(group_members)) %>%
  mutate(linking_group = as.numeric(linking_group)) %>%
  mutate(house = as.character(house))
glimpse(sheet)
```


```{r assign_id}

# unneeded in randomizer_real

# each student is given a
# temporary id. This is used
# to shuffle students later
# on in the code. When the
# ids are reassigned and arranged,
# then the order of students changes.
# This ensures that variables
# in the fake data are 
# random (not correlated).

mutate(sheet, id = 1:1639)
randomize_id <- function(){
  num_list = sample.int(n = 1639, size = 1639)
  sheet %>% 
    mutate(id = num_list) %>% 
    arrange(id)
}
```

```{r assign_attributes}

# unneeded in randomizer_real

# assigns most of the variables
# to the fake data set. First, the percentage
# of a specific variable's distribution
# is calculated. Then values for that variable
# are assigned based on the variable's distribution.
# Before the next variable is assigned, the 
# IDs are randomized. This ensures that not all 
# males (assigned to the first 50% of the
# data) are also White or Asian (assigned to the 
# first 61% of the data). Otherwise, all variables 
# would be correlated.

# assign sex 
# 0 = m: 50% (819)
# 1 = f: 50% (820)
sheet <- randomize_id()
sheet <- mutate(sheet, sex = rep(c(0, 1), c(819, 820)))

# assign ethnicity
# 1 = White: 44% (721)
# 2 = Asian: 17% (280)
# 3 = Black: 11% (180)
# 4 = Hispanic/LatinX: 11% (180)
# 5 = Middle Eastern/North African 2% (33)
# 6 = Indigenous/Native American: 1% (16)
# 7 = Prefer not to say: 7% (115)
# 8 = Other: 7% (114)
sheet <- randomize_id()
sheet <- mutate(sheet, ethnicity = rep(c(1, 2, 3, 4, 5, 6, 7, 8), c(721, 280, 180, 180, 33, 16, 115, 114))) 

# assign religion
# 1 = Agnostic: 21% (344)
# 2 = Christian: 34% (557)
# 3 = Atheist: 17% (279)
# 4 = Jewish: 10% (160)
# 5 = Hindu: 3% (49)
# 6 = Muslim: 3% (49)
# 7 = Prefer not to say: 6% (101)
# 8 = Other: 6% (100)
sheet <- randomize_id()
sheet <- mutate(sheet, religion = rep(c(1, 2, 3, 4, 5, 6, 7, 8), c(344, 557, 279, 160, 49, 49, 101, 100)))
  
# assign sexual_orientation
# 1 = Heterosexual: 82% (1344)
# 2 = Homosexual: 7% (115)
# 3 = Bisexual: 7% (115)
# 4 = Asexual: 1% (16)
# 5 = Prefer not to say: 2% (32)
# 6 = Other: 1% (17)
sheet <- randomize_id()
sheet <- mutate(sheet, sexual_orientation = rep(c(1, 2, 3, 4, 5, 6), c(1344, 115, 115, 16, 32, 17)))
  
# assign international
# 0 = Domestic: 88% (1345)
# 1 = International: 18% (294)
sheet <- randomize_id()
sheet <- mutate(sheet, international = rep(c(0,1), c(1345, 294))) 

# assign legacy
# 0 = no: 86% (1410)
# 1 = yes: 14% (229)
sheet <- randomize_id()
sheet <- mutate(sheet, legacy = rep(c(0,1), c(1410, 229))) 

# assign financial aid
# 0 = no: 45% (738)
# 1 = yes: 55% (901)
sheet <- randomize_id()
sheet <- mutate(sheet, financial_aid = rep(c(0,1), c(738, 901))) 

# assign suitemates
# 0 = no: 85% (1393)
# 1 = yes: 15% (246)
sheet <- randomize_id()
sheet <- mutate(sheet, suitemates = rep(c(0,1), c(1393, 246))) 

# assign group_size and group_name
# 1: 8% (130)
# 2: 6% (98)
# 3: 7% (114)
# 4: 11% (180)
# 5: 12% (195)
# 6: 20% (330)
# 7: 17% (280)
# 8: 19% (312)


# first I assign group sizes to everyone
# in the dataset. Next, a group_name is 
# assigned to everyone. I assign group
# name using rep(x, y) where I go through
# rep range x, y times. 

sheet <- randomize_id()
sheet <- mutate(sheet, 
                group_size = rep(c(1, 2, 3, 4, 5, 6, 7, 8), c(130, 98, 114, 180, 195, 330, 280, 312)),
                group_name = c(rep(1:130, 1),
                        rep(131:179, 2), 
                        
                        # missing group 180
                        
                        rep(181:218, 3),
                        rep(219:263, 4),
                        rep(264:302, 5),
                        rep(303:357, 6),
                        rep(358:397, 7),
                        rep(398:436, 8)
                        ))
# varsity athlete?
sheet <- sheet %>% 
  mutate(varsity = ifelse(!is.na(sport), TRUE, FALSE))
```


```{r calculate_house_size}
# create houses
# respondent is the variable name of the total number of respondents. 
# Here we find number of people in our sample that are supposed to be in each house 
# We begin by listing the cutoff number of students in each house
respondents <- sheet %>%
  count() %>%
  pull()
total_uppseclassmen <- 4527
num_adams <- round(263 / total_uppseclassmen * respondents, 0)
num_cabot <- round((263+357) / total_uppseclassmen * respondents, 0)
num_currier <- round((263+357+364) / total_uppseclassmen * respondents, 0)
num_dunster <- round((263+357+364+376) / total_uppseclassmen * respondents,0)
num_eliot <- round((263+357+364+376+425) / total_uppseclassmen * respondents, 0)
num_kirkland <- round((263+357+364+376+425+386) / total_uppseclassmen * respondents, 0)
num_leverett <- round((263+357+364+376+425+386+322) / total_uppseclassmen * respondents, 0)
num_lowell <- round((263+357+364+376+425+386+322+407) / total_uppseclassmen * respondents, 0)
num_mather <- round((263+357+364+376+425+386+322+407+399) / total_uppseclassmen * respondents, 0)
num_pfoho <- round((263+357+364+376+425+386+322+407+399+365) / total_uppseclassmen * respondents, 0)
num_quincy <- round((263+357+364+376+425+386+322+407+399+365+465) / total_uppseclassmen * respondents, 0)
num_winthrop <- round((263+357+364+376+425+386+322+407+399+365+465+398) / total_uppseclassmen * respondents, 0)
```


```{r assign_houses}

# assign houses

# takes in sheet and assigns houses randomly. group_name
# has to be unique because we group_by the group_name, but
# it does not have to be a numerical variable. The group_name
# can be anything.

assign_houses <- function(sheet = sheet){
  grouped <- sheet %>% 
    mutate(random_house = "") %>% 
    group_by(group_name) %>% 
    slice(1)
  
  rows <- sample(nrow(grouped))
  grouped <- grouped[rows, ]
  
  count <- 0
  for (row in 1:nrow(grouped)) {
      if((count + grouped[row,"group_size"] )<= num_adams) {
          grouped[row,"random_house"]<- "Adams"
          count <- count+ grouped[row,"group_size"]
      }
        
      else if(num_adams < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_cabot) {
          grouped[row,"random_house"]<- "Cabot"
          count <- count+ grouped[row,"group_size"]
      }
      
      else if (num_cabot < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_currier){ grouped[row,"random_house"]<- "Currier"
           count <- count+ grouped[row,"group_size"]}
  
      else if (num_currier < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_dunster){ grouped[row,"random_house"]<- "Dunster"
           count <- count+ grouped[row,"group_size"]}
    
      else if (num_dunster < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_eliot){ grouped[row,"random_house"]<- "Eliot"
           count <- count+ grouped[row,"group_size"]}
    
      else if (num_eliot < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_kirkland){ grouped[row,"random_house"]<- "Kirkland"
           count <- count+ grouped[row,"group_size"]}
    
      else if (num_kirkland < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_leverett){ grouped[row,"random_house"]<- "Leverett"
           count <- count+ grouped[row,"group_size"]}
    
      else if (num_leverett < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_lowell){ grouped[row,"random_house"]<- "Lowell"
           count <- count+ grouped[row,"group_size"]}
    
      else if (num_lowell < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_mather){ grouped[row,"random_house"]<- "Mather"
           count <- count+ grouped[row,"group_size"]}
    
      else if (num_mather < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_pfoho){ grouped[row,"random_house"]<- "Pfoho"
           count <- count+ grouped[row,"group_size"]}
    
      else if (num_pfoho < (count + grouped[row,"group_size"] ) & (count + grouped[row,"group_size"] ) <= num_quincy){ grouped[row,"random_house"]<- "Quincy"
           count <- count+ grouped[row,"group_size"]}
    
      else {grouped[row,"random_house"]<- "Winthrop"}
  }
    
  # combines the original sheet with the "grouped" sheet
  # which assigns the house to the first person in every bloc.
  # Once these two are joined, every person in the original
  # sheet has a house.
  
  assigned_all <- left_join(sheet, grouped, by = "group_name") %>% 
  select(1:23, 46) %>%
  rename_at(.vars = vars(ends_with(".x")),
            .funs = funs(sub("[.]x$", "", .))) %>%
  mutate(house = random_house) %>%
  select(-random_house)
  
  # returns assigned_all which contains house assignments
  # for every person in the original first_years spreadsheet.
  
  assigned_all
}
```

```{r overview_function}

# generates summary statistics for any identifiable community. 
# It takes in a sheet of assigned houses and then also takes
# in a community within the assigned sheet that you would like
# to filter for. It takes in assigned as a variable because 
# later we use a map function to pass in a unique set of assigned
# houses.
#
# summary statistics are returned in the form of a tibble

# cycle through all the houses, don't fill one out completely
# and then fill out the next house because it might skew the
# distribution of group_size.

overview <- function(assigned, community){
    
  if(community == "river_central"){
    community <- assigned %>%
    filter(house == "Lowell" | house == "Quincy" | house == "Adams")
  }

  else if(community == "river_east"){
    community <- assigned %>%
      filter(house == "Leverett" | house == "Dunster" | house == "Mather")
  }

  else if(community == "river_west"){
    community <- assigned %>%
      filter(house == "Eliot" | house == "Winthrop" | house == "Kirkland")
  }
  
  else if(community == "river"){
    community <- assigned %>%
    filter(house == "Lowell" | house == "Quincy" | house == "Adams" | house == "Leverett" | house == "Dunster" | house == "Mather" | house == "Eliot" | house == "Winthrop" | house == "Kirkland")
  }

  else if(community == "quad"){
    community <- assigned %>%
      filter(house == "Pfoho" | house == "Cabot" | house == "Currier")
  }

  else{
    community <- assigned %>%
    filter(house == community)
  }
  
  # the method in which summary statistics are generated still needs to
  # be modified. Considering making a tibble for all categorical variables
  # like ethnicity or religion. This might be complicated because when we 
  # use this function within a map on an already existing tibble, we will have
  # a tibble (the tibble of ethnicity/religion distribution) within a tibble 
  # (the tibble of summary statistics) within a tibble (the tibble of random 
  # house assignment replicates). 
  
  tibble(
    prop_sex = mean(community$sex),
    prop_international = mean(community$international),
    prop_varsity = mean(community$varsity),
    prop_legacy = mean(community$legacy),
    prop_financial_aid = mean(community$financial_aid),
    prop_group_size = mean(community$group_size),
    prop_white = community %>%
      filter(ethnicity == 1) %>% 
      count() %>%
      pull()/nrow(community)
  )
  # prop_ethnicity 
  # prop_religion
  # prop_sexual_orientation
  
  # consider separating out categorical variables 
  # and creating separate plots
  
  # can do individual ethnicities or put together
  # a tibble with all of the ethnicities.
  
}

```

```{r confidence_interval}

# function to caluculate confidence intervals 
# that takes in the lower percentile and the
# upper percentile. A community must be passed
# in that has already had overview() called on it.
confidence_interval <- function(community, lower_percentile = 0.025, median = 0.5, upper_percentile = 0.975){
  percentiles <- tibble(
    percentile = c(lower_percentile, median, upper_percentile),
    prop_sex = quantile(community %>% ungroup() %>% pull(prop_sex), c(lower_percentile, median, upper_percentile)),
    prop_international = quantile(community %>% ungroup() %>% pull(prop_international), c(lower_percentile, median, upper_percentile)),
    prop_varsity = quantile(community %>% ungroup() %>% pull(prop_varsity), c(lower_percentile, median, upper_percentile)),
    prop_legacy = quantile(community %>% ungroup() %>% pull(prop_legacy), c(lower_percentile, median, upper_percentile)),
    prop_financial_aid = quantile(community %>% ungroup() %>% pull(prop_financial_aid), c(lower_percentile, median, upper_percentile)),
    prop_group_size = quantile(community %>% ungroup() %>% pull(prop_group_size), c(lower_percentile, median, upper_percentile))   
  )
  percentiles
}
```


```{r all_communities}

# creates a tibble of all communities (neighborhoods AND houses)
# n times where n represents the number of reps in the rep_sample_n.
# This tibble is then used to generate summary statistics for 
# each community. It relies on the previous functions for
# (1) assigning houses and (2) generating summary statistics.
#
# This tibble can be filtered down for any desired sub communities
# as done in later r code chunks


all_communities <- sheet %>% 
  
  # 1) replicate the sheet of freshmen and group_by each replicate
  
  rep_sample_n(size = nrow(sheet), replace = FALSE, reps = 10) %>% 
  group_by(replicate)  %>% 
  nest() %>% 
  
  # 2) take each tibble of freshmen and assign houses
  
  mutate(assigned = map(data,~assign_houses(sheet = .))) %>% 
  
  # 3) take each tibble of "assigned" freshmen and generate community summaries
  
  # neighborhoods
  mutate(river_central = map(assigned, ~overview(assigned = ., community = 'river_central'))) %>% 
  mutate(river_east = map(assigned, ~overview(assigned = ., community = 'river_east'))) %>% 
  mutate(river_west = map(assigned, ~overview(assigned = ., community = 'river_west'))) %>% 
  mutate(river = map(assigned, ~overview(assigned = ., community = 'river'))) %>% 
  mutate(quad = map(assigned, ~overview(assigned = ., community = 'quad'))) %>% 
  
  #river_central
  mutate(adams = map(assigned, ~overview(assigned = ., community = 'Adams'))) %>% 
  mutate(lowell = map(assigned, ~overview(assigned = ., community = 'Lowell'))) %>% 
  mutate(quincy = map(assigned, ~overview(assigned = ., community = 'Quincy'))) %>% 
  
  
  # river_east
  mutate(leverett = map(assigned, ~overview(assigned = ., community = 'Leverett'))) %>% 
  mutate(dunster = map(assigned, ~overview(assigned = ., community = 'Dunster'))) %>% 
  mutate(mather = map(assigned, ~overview(assigned = ., community = 'Mather'))) %>%  
  
  
  # river_west
  mutate(winthrop = map(assigned, ~overview(assigned = ., community = 'Winthrop'))) %>% 
  mutate(kirkland = map(assigned, ~overview(assigned = ., community = 'Kirkland'))) %>% 
  mutate(eliot = map(assigned, ~overview(assigned = ., community = 'Eliot'))) %>%   
  
  
  # quad
  mutate(currier = map(assigned, ~overview(assigned = ., community = 'Currier'))) %>% 
  mutate(pfoho = map(assigned, ~overview(assigned = ., community = 'Pfoho'))) %>% 
  mutate(cabot = map(assigned, ~overview(assigned = ., community = 'Cabot'))) 

```

```{r neighborhoods}

# generates summary statistics for neighborhoods

neighborhoods <- all_communities %>% 
  select(replicate, river_central, river_east, river_west, quad) 

river_central <- all_communities %>% 
  select(replicate, river_central) %>% 
  unnest(river_central)

river_east <- all_communities %>% 
  select(replicate, river_east) %>% 
  unnest(river_east)

river_west <- all_communities %>% 
  select(replicate, river_west) %>% 
  unnest(river_west)

river <- all_communities %>% 
  select(replicate, river) %>% 
  unnest(river)

quad <- all_communities %>% 
  select(replicate, quad) %>% 
  unnest(quad)
```

```{r analysis}

ci_river <- confidence_interval(river)
ci_river

ci_quad <- confidence_interval(quad)
ci_quad


# river <- confidence_interval(all_communities %>% select(replicate, quincy) %>% unnest(quincy))


#   write_excel_csv2(path = 'quincy.csv') %>% 
# 
# convert("quincy.csv", "quincy.xlsx")

# 1 - 0.95^12

# is there evidence that athletes are randomly distributed across all 12 houses.
# If athletes are randomly distributed, some houses will be above, and some will be
# below. You need a sum of the deviation from the mean for all houses --> sum of squared 
# differences of the mean for the houses. 

```



```{r saveRDS}
# saveRDS(object = all_communities, file = "shiny_app/updated_fake_data.RDS")
# saveRDS(object = river, file = "shiny_app/updated_fake_data.RDS")
# saveRDS(object = quad, file = "shiny_app/updated_fake_data.RDS")
# saveRDS(object = river_central, file = "shiny_app/updated_fake_data.RDS")
# saveRDS(object = river_east, file = "shiny_app/updated_fake_data.RDS")
# saveRDS(object = river_west, file = "shiny_app/updated_fake_data.RDS")

saveRDS(object = assigned_all, file = "shiny_app/updated_fake_data.RDS")
```







