---
title: "Blocking Group Project - MS3"
author: "Jamal Nimer, Sam Saba, Lucy He, Eliot Min, Angie Shin, Austin Li, Shojeh Liu, Carina Peng, Ilyas Mardin"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Repo HTML:
https://github.com/Lumos23/gov-1005-final-project

# About Section:
This project aims to continue the work of the previous blocking group project with more rigorous data analytics and statistical computation, more intuitive graph design, and additional questions (including sexual orientation). It will hopefully build on the previous analysis attempting to find any discrepancies. 

The project will attempt to replicate a truly random housing lottery to assess if Harvard's housing appears to be random as well. The project will check variables such as legacy, race, religion, athletics, sex, freshman dorm, financial aid, international students, and blocking group size.

All Sensitive questions have a "prefer not to answer" option

# Modified Survey:

Email

Name

Freshman dorm

Entryway

Sex

Race/Ethnicity (check all that apply)

Religion

Sexual Orientation

International

Athlete

Legacy

Financial aid

First-generation college student

Blocking group leader (First name last name)

Blocking group name (enter all lowercase with no spaces)

Blocking group size

Members of your blocking group (first name and last name, separate names with commas John Harvard, Samuel Pennypacker, Smith Wigglesworth)

Assigned House

First and last name of one person from your linking group
