---
title: "real_data"
author: "Jamal Nimer, Lucy He, Austin Li"
date: "4/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(readxl)
library(reprex)
library(janitor)
library(gt)
library(haven)
library(shiny)
library(infer)
library(dplyr)
library(googlesheets4)
```

```{r}
# reads in from the "first_years"
# google sheet in the project drive

sheets_deauth()
  
ss1 <- 'https://docs.google.com/spreadsheets/d/1edQVynHA0j7Dnnth8qTvQtmS3ww768lyl4pyPC8XPoE/edit?usp=sharing'

official_housing <- read_sheet(ss1) 

```

```{r overview_function}

# generates summary statistics for any identifiable community. 
# It takes in a sheet of assigned houses and then also takes
# in a community within the assigned sheet that you would like
# to filter for. It takes in assigned as a variable because 
# later we use a map function to pass in a unique set of assigned
# houses.
#
# summary statistics are returned in the form of a tibble

overview <- function(assigned, community){
    
  if(community == "river_central"){
    community <- assigned %>%
    filter(house == "Lowell" | house == "Quincy" | house == "Adams")
  }

  else if(community == "river_east"){
    community <- assigned %>%
      filter(house == "Leverett" | house == "Dunster" | house == "Mather")
  }

  else if(community == "river_west"){
    community <- assigned %>%
      filter(house == "Eliot" | house == "Winthrop" | house == "Kirkland")
  }
  
  else if(community == "river"){
    community <- assigned %>%
    filter(house == "Lowell" | house == "Quincy" | house == "Adams" | house == "Leverett" | house == "Dunster" | house == "Mather" | house == "Eliot" | house == "Winthrop" | house == "Kirkland")
  }

  else if(community == "quad"){
    community <- assigned %>%
      filter(house == "Pforzheimer" | house == "Cabot" | house == "Currier")
  }

  else{
    community <- assigned %>%
    filter(house == community)
  }
  
  # the method in which summary statistics are generated still needs to
  # be modified. Considering making a tibble for all categorical variables
  # like ethnicity or religion. This might be complicated because when we 
  # use this function within a map on an already existing tibble, we will have
  # a tibble (the tibble of ethnicity/religion distribution) within a tibble 
  # (the tibble of summary statistics) within a tibble (the tibble of random 
  # house assignment replicates). 
  
  tibble(
    prop_international = mean(community$international, na.rm = TRUE),
    prop_varsity = mean(community$varsity, na.rm = TRUE),
    prop_legacy = mean(community$legacy, na.rm = TRUE),
    prop_financial_aid = mean(community$financial_aid, na.rm = TRUE),
    prop_group_size = mean(community$group_size, na.rm = TRUE)
  )
  # prop_ethnicity
  # prop_religion
  # prop_sexual_orientation
  # prop_gender = mean(community$gender, na.rm = TRUE))

  
  # consider separating out categorical variables 
  # and creating separate plots
  
  # can do individual ethnicities or put together
  # a tibble with all of the ethnicities.
  
}

```


```{r all_communities}

# creates a tibble of all communities (neighborhoods AND houses)
# n times where n represents the number of reps in the rep_sample_n.
# This tibble is then used to generate summary statistics for 
# each community. It relies on the previous functions for
# (1) assigning houses and (2) generating summary statistics.
#
# This tibble can be filtered down for any desired sub communities
# as done in later r code chunks

all_communities <- official_housing %>% 
  
  # 1) take the sheet of freshman and nest
  nest(data=everything()) %>% 
  
  # 2) take each tibble of "assigned" freshmen and generate community summaries
  
  # neighborhoods
  mutate(river_central = map(data, ~overview(assigned = ., community = 'river_central'))) %>% 
  mutate(river_east = map(data, ~overview(assigned = ., community = 'river_east'))) %>% 
  mutate(river_west = map(data, ~overview(assigned = ., community = 'river_west'))) %>% 
  mutate(river = map(data, ~overview(assigned = ., community = 'river'))) %>% 
  mutate(quad = map(data, ~overview(assigned = ., community = 'quad'))) %>% 
  
  #river_central
  mutate(adams = map(data, ~overview(assigned = ., community = 'Adams'))) %>% 
  mutate(lowell = map(data, ~overview(assigned = ., community = 'Lowell'))) %>% 
  mutate(quincy = map(data, ~overview(assigned = ., community = 'Quincy'))) %>% 
  
  
  # river_east
  mutate(leverett = map(data, ~overview(assigned = ., community = 'Leverett'))) %>% 
  mutate(dunster = map(data, ~overview(assigned = ., community = 'Dunster'))) %>% 
  mutate(mather = map(data, ~overview(assigned = ., community = 'Mather'))) %>%  
  
  
  # river_west
  mutate(winthrop = map(data, ~overview(assigned = ., community = 'Winthrop'))) %>% 
  mutate(kirkland = map(data, ~overview(assigned = ., community = 'Kirkland'))) %>% 
  mutate(eliot = map(data, ~overview(assigned = ., community = 'Eliot'))) %>%   
  
  
  # quad
  mutate(currier = map(data, ~overview(assigned = ., community = 'Currier'))) %>% 
  mutate(pforzheimer = map(data, ~overview(assigned = ., community = 'Pforzheimer'))) %>% 
  mutate(cabot = map(data, ~overview(assigned = ., community = 'Cabot'))) 

```

```{r neighborhoods}

# generates summary statistics for neighborhoods

neighborhoods <- all_communities %>% 
  select(river_central, river_east, river_west, quad) 

river_central <- all_communities %>% 
  select(river_central) %>% 
  unnest(river_central)

river_east <- all_communities %>% 
  select(river_east) %>% 
  unnest(river_east)

river_west <- all_communities %>% 
  select(river_west) %>% 
  unnest(river_west)

river <- all_communities %>% 
  select(river) %>% 
  unnest(river)

quad <- all_communities %>% 
  select(quad) %>% 
  unnest(quad)
```

```{r analysis}

river
quad

# use a chisq.test(x = a numeric vector or matrix,
#                  y = a vector, ignored if x is a matrix)

```


```{r saveRDS}
# saveRDS(object = assigned_all, file = "shiny_app/updated_fake_data.RDS")
```


```{r prop function, echo=F}
# determining proportions
# general prop function

prop <- function(list1,list2) {
  length(list1)/length(list2)
}
```


```{r ethnicity, echo=F}

# ethnicity
# selecting rows into a list

w <- which(grepl("White", official_housing$ethnicity))

a <- which(grepl("Asian", official_housing$ethnicity))

b <- which(grepl("Black", official_housing$ethnicity))

hl <- which(grepl("Hispanic/Latinx", official_housing$ethnicity))

mena <- which(grepl("Middle Eastern/North African", official_housing$ethnicity))

indna <- which(grepl("Indigenous/Native American", official_housing$ethnicity))

eth_pref <- which(grepl("Prefer not to say", official_housing$ethnicity))

# total ethnicities reported

total_ethnicity = c(w, a, b, hl, mena, indna, eth_pref)

# ethinicity proportions table

prop_ethnicity_tibble <- tibble(
  prop_white = prop(w, total_ethnicity),
  prop_asian = prop(a, total_ethnicity),
  prop_black = prop(b, total_ethnicity),
  prop_hl = prop(hl, total_ethnicity),
  prop_mena = prop(mena, total_ethnicity),
  prop_indna = prop(indna, total_ethnicity),
  prop_eth_pref = prop(eth_pref, total_ethnicity)
)

prop_ethnicity_tibble
```

```{r religion, echo=F}
christ <- which(grepl("Christian", official_housing$religion))

hindu <- which(grepl("Hindu", official_housing$religion))

muslim <- which(grepl("Muslim", official_housing$religion))

jewish <- which(grepl("Jewish", official_housing$religion))

agnos <- which(grepl("Agnostic", official_housing$religion))

athiest <- which(grepl("Athiest", official_housing$religion))

relig_pref <- which(grepl("Prefer not to say", official_housing$religion))

# total religions reported

total_relig = c(christ, hindu, muslim, jewish, agnos, athiest, relig_pref)

# religion proportions table

prop_relig_table <- tibble(
  prop_christ = prop(christ, total_relig),
  prop_hindu = prop(hindu, total_relig),
  prop_muslim = prop(muslim, total_relig),
  prop_jewish = prop(jewish, total_relig),
  prop_agnos = prop(agnos, total_relig),
  prop_athiest = prop(athiest, total_relig),
  prop_relig_pref = prop(relig_pref, total_relig)
)

prop_relig_table
```

```{r sex_or, echo=F}
hetero <- which(grepl("Heterosexual", official_housing$sexual_orientation))

homo <- which(grepl("Homosexual", official_housing$sexual_orientation))

bi <- which(grepl("Bisexual", official_housing$sexual_orientation))

as <- which(grepl("Asexual", official_housing$sexual_orientation))

sex_pref <- which(grepl("Prefer not to say", official_housing$sexual_orientation))

# total sexual orientations reported

total_sex <- c(hetero, homo, bi, as, sex_pref)

# sexual orientation proportions table

prop_sex_tibble <- tibble(
  prop_hetero = prop(hetero, total_sex),
  prop_homo = prop(homo, total_sex),
  prop_bi = prop(bi, total_sex),
  prop_as = prop(as, total_sex),
  prop_sex_pref = prop(sex_pref, total_sex)
)

prop_sex_tibble
```

```{r reason_suitemates, echo=F}

# blocking with suitemates

suite_yes <- which(grepl("Yes", official_housing$suitemates))

suite_no <- which(grepl("No", official_housing$suitemates))

# total suite

total_suite <- c(suite_yes, suite_no)

# blocking with suitemates proportions table

prop_suite_tibble <- tibble(
  prop_suite_yes = prop(suite_yes, total_suite),
  prop_suite_no = prop(suite_no, total_suite)
)

# reason for blocking with suitemates

sleep <- which(grepl("Similar sleeping schedules", official_housing$reason_suitemates))

aca_int <- which(grepl("Common academic interests", official_housing$reason_suitemates))

hobbies <- which(grepl("Common hobbies", official_housing$reason_suitemates))

friends <- which(grepl("Similar friend groups", official_housing$reason_suitemates))

music <- which(grepl("Same taste for music", official_housing$reason_suitemates))

religion <- which(grepl("Same religion", official_housing$reason_suitemates))

# total suite_reasons reported

total_suite_reasons <- c(sleep, aca_int, hobbies, friends, music, religion)

# blocking with suitemates reason proportions table

prop_suite_reason_tibble <- tibble(
  prop_sleep = prop(sleep, total_suite_reasons),
  prop_aca_int = prop(aca_int, total_suite_reasons),
  prop_hobbies = prop(hobbies, total_suite_reasons),
  prop_friends = prop(friends, total_suite_reasons),
  prop_music = prop(music, total_suite_reasons),
  prop_reigion = prop(religion, total_suite_reasons)
)

prop_suite_tibble
prop_suite_reason_tibble

```

```{r group_size, echo=F}
one <- which(grepl(1, official_housing$group_size))

two <- which(grepl(2, official_housing$group_size))

three <- which(grepl(3, official_housing$group_size))

four <- which(grepl(4, official_housing$group_size))

five <- which(grepl(5, official_housing$group_size))

six <- which(grepl(6, official_housing$group_size))

seven <- which(grepl(7, official_housing$group_size))

eight <- which(grepl(8, official_housing$group_size))

# total sizes reported

total_sizes <- c(one, two, three, four, five, six, seven, eight)

# group size proportions table

prop_group_size_tibble <- tibble(
  prop_one = prop(one, total_sizes),
  prop_two = prop(two, total_sizes),
  prop_three = prop(three, total_sizes),
  prop_four = prop(four, total_sizes),
  prop_five = prop(five, total_sizes),
  prop_six = prop(six, total_sizes),
  prop_seven = prop(seven, total_sizes),
  prop_eight = prop(eight, total_sizes)
)
```

```{r appr, echo=F}
app_yes <- which(grepl(1, official_housing$approval))

app_no <- which(grepl(0, official_housing$approval))

# total approval reported

total_app = c(app_yes, app_no)

# approval proportions table

prop_approve <- tibble(
  prop_app_yes = prop(app_yes, total_app),
  prop_app_no = prop(app_no, total_app)
)

prop_approve
```

```{r total proportions, echo=F}

# view all demographic statistics

total_proportions = tibble(
  ethnicity = prop_ethnicity_tibble,
  religion= prop_relig_table,
  sexual_orientation = prop_sex_tibble,
  block_w_suitemates = prop_suite,
  suitemates_reason = prop_suite_reason_tibble,
  group_size = prop_group_size_tibble,
  approval = prop_approve
)

total_proportions
```


